# initialize_db.py
import sqlite3

def initialize_database():
    connection = sqlite3.connect('app.db')
    cursor = connection.cursor()

    cursor.execute('DROP TABLE IF EXISTS word_practice_log')
    cursor.execute('DROP TABLE IF EXISTS words')
    cursor.execute('DROP TABLE IF EXISTS courses')


    cursor.execute('''
        CREATE TABLE IF NOT EXISTS courses (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL
        )
    ''')

    cursor.execute('''
        CREATE TABLE IF NOT EXISTS words (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            course_id INTEGER,
            word_pl TEXT,
            word_en TEXT,
            example_pl TEXT,
            example_en TEXT,
            category TEXT,
            correct_count INTEGER DEFAULT 0,
            next_review_date TEXT,
            FOREIGN KEY(course_id) REFERENCES courses(id)
        )
    ''')


    cursor.execute('''
        CREATE TABLE IF NOT EXISTS word_practice_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            word_id INTEGER,
            practice_date TEXT,
            FOREIGN KEY(word_id) REFERENCES words(id)
        )
    ''')


    courses = [("A1",), ("A2",), ("B1",), ("B2",)]
    cursor.executemany("INSERT INTO courses (name) VALUES (?)", courses)

    # Słownik mapujący nazwy kursów na ich ID
    course_ids = {}
    cursor.execute("SELECT id, name FROM courses")
    for row in cursor.fetchall():
        course_ids[row[1]] = row[0]

    # Dodawanie słówek do kursu A1
    course_id = course_ids['A1']
    words_a1 = [
        (course_id, "dom", "house",
         "Mieszkam w pięknym, dużym domu na przedmieściach, gdzie mam ciszę i spokój.",
         "I live in a beautiful, large ... in the suburbs, where I have peace and quiet.",
         "NOWE"),
        (course_id, "kot", "cat",
         "Nasz kot codziennie rano wskakuje na łóżko, aby nas obudzić swoim głośnym miauczeniem.",
         "Our ... jumps on the bed every morning to wake us up with its loud meowing.",
         "NOWE"),
        (course_id, "pies", "dog",
         "Pies sąsiada uwielbia biegać po ogrodzie i bawić się z dziećmi.",
         "The neighbor's ... loves running in the garden and playing with the children.",
         "NOWE"),
        (course_id, "szkoła", "school",
         "Chodzę do szkoły od poniedziałku do piątku, a weekendy spędzam na odpoczynku.",
         "I go to ... from Monday to Friday, and I spend weekends resting.",
         "NOWE"),
        (course_id, "samochód", "car",
         "Codziennie rano jadę do pracy samochodem i zwykle stoję w korkach.",
         "Every morning I drive to work by ... and usually sit in traffic.",
         "NOWE"),
        (course_id, "kwiat", "flower",
         "W ogrodzie mamy wiele pięknych kwiatów, które kwitną na wiosnę.",
         "In our garden, we have many beautiful ... that bloom in spring.",
         "NOWE"),
        (course_id, "książka", "book",
         "Ta książka jest tak ciekawa, że nie mogłem jej odłożyć.",
         "This ... is so interesting that I couldn't put it down.",
         "NOWE"),
        (course_id, "rower", "bicycle",
         "Często jeżdżę rowerem po parku, aby zachować dobrą kondycję.",
         "I often ride my ... in the park to stay fit.",
         "NOWE"),
        (course_id, "miasto", "city",
         "Moje miasto jest pełne zabytków i ciekawych miejsc.",
         "My ... is full of monuments and interesting places.",
         "NOWE"),
        (course_id, "dziecko", "child",
         "Małe dziecko w parku bawi się na placu zabaw.",
         "A small ... is playing on the playground in the park.",
         "NOWE"),
        (course_id, "nauczyciel", "teacher",
         "Mój nauczyciel matematyki zawsze wyjaśnia trudne zagadnienia.",
         "My math ... always explains difficult topics.",
         "NOWE"),
        (course_id, "krzesło", "chair",
         "Kupiliśmy nowe krzesła do jadalni.",
         "We bought new ... for the dining room.",
         "NOWE"),
        (course_id, "okno", "window",
         "Przez okno widzę piękny krajobraz górski.",
         "Through the ..., I see a beautiful mountain landscape.",
         "NOWE"),
        (course_id, "drzewo", "tree",
         "W parku rośnie wiele starych drzew.",
         "There are many old ... growing in the park.",
         "NOWE"),
        (course_id, "domowy", "home",
         "Lubię spędzać czas w domowym zaciszu.",
         "I like spending time in the comfort of my ....",
         "NOWE"),
        (course_id, "mleko", "milk",
         "Każdego ranka piję szklankę mleka.",
         "Every morning I drink a glass of ....",
         "NOWE"),
        (course_id, "tata", "dad",
         "Mój tata jest bardzo pracowity i zawsze mi pomaga.",
         "My ... is very hardworking and always helps me.",
         "NOWE"),
        (course_id, "mama", "mom",
         "Moja mama przygotowuje pyszne posiłki.",
         "My ... prepares delicious meals.",
         "NOWE"),
        (course_id, "stół", "table",
         "Na stole leży świeży chleb i owoce.",
         "There is fresh bread and fruits on the ....",
         "NOWE"),
        (course_id, "telewizor", "television",
         "Wieczorem oglądamy filmy na dużym telewizorze.",
         "In the evening, we watch movies on the big ....",
         "NOWE"),
        (course_id, "piłka", "ball",
         "Dzieci grają w piłkę na boisku.",
         "Children are playing with a ... on the field.",
         "NOWE"),
        (course_id, "praca", "work",
         "Moja praca sprawia mi dużo satysfakcji.",
         "My ... gives me a lot of satisfaction.",
         "NOWE"),
        (course_id, "kawa", "coffee",
         "Lubię zaczynać dzień od filiżanki kawy.",
         "I like to start the day with a cup of ....",
         "NOWE"),
        (course_id, "rzeka", "river",
         "Spacerujemy wzdłuż rzeki, podziwiając widoki.",
         "We walk along the ..., admiring the views.",
         "NOWE"),
        (course_id, "dach", "roof",
         "Ptak usiadł na dachu naszego domu.",
         "A bird sat on the ... of our house.",
         "NOWE"),
        (course_id, "zegar", "clock",
         "Zegar na ścianie wybija południe.",
         "The ... on the wall strikes noon.",
         "NOWE"),
        (course_id, "lampa", "lamp",
         "Potrzebujemy nowej lampy do salonu.",
         "We need a new ... for the living room.",
         "NOWE"),
        (course_id, "podłoga", "floor",
         "Podłoga w kuchni jest czysta i błyszcząca.",
         "The ... in the kitchen is clean and shiny.",
         "NOWE"),
        (course_id, "łóżko", "bed",
         "Po długim dniu marzę tylko o swoim łóżku.",
         "After a long day, I only dream about my ....",
         "NOWE"),
        (course_id, "jedzenie", "food",
         "Restauracja oferuje pyszne jedzenie.",
         "The restaurant offers delicious ....",
         "NOWE"),
        (course_id, "słońce", "sun",
         "Słońce świeci jasno na bezchmurnym niebie.",
         "The ... shines brightly in the cloudless sky.",
         "NOWE"),
    ]

    # Dodawanie słówek do kursu A2
    course_id = course_ids['A2']
    words_a2 = [
        (course_id, "podróż", "journey",
         "Nasza podróż pociągiem do Krakowa była pełna przygód.",
         "Our ... by train to Krakow was full of adventures.",
         "NOWE"),
        (course_id, "muzeum", "museum",
         "Odwiedziliśmy muzeum sztuki współczesnej w weekend.",
         "We visited the modern art ... over the weekend.",
         "NOWE"),
        (course_id, "teatr", "theater",
         "Wczoraj byliśmy w teatrze na nowej sztuce.",
         "Yesterday we were at the ... watching a new play.",
         "NOWE"),
        (course_id, "księgarnia", "bookstore",
         "Kupiłem nową powieść w lokalnej księgarni.",
         "I bought a new novel at the local ....",
         "NOWE"),
        (course_id, "kawiarnia", "café",
         "Spotkajmy się w kawiarni na rogu o 15:00.",
         "Let's meet at the ... on the corner at 3 PM.",
         "NOWE"),
        (course_id, "przyszłość", "future",
         "Martwię się o swoją przyszłość zawodową.",
         "I'm worried about my professional ....",
         "NOWE"),
        (course_id, "pogoda", "weather",
         "Dzisiejsza pogoda jest idealna na spacer.",
         "Today's ... is perfect for a walk.",
         "NOWE"),
        (course_id, "spotkanie", "meeting",
         "Mam ważne spotkanie z klientem o 10:00.",
         "I have an important ... with a client at 10 AM.",
         "NOWE"),
        (course_id, "informacja", "information",
         "Potrzebuję więcej informacji na ten temat.",
         "I need more ... on this topic.",
         "NOWE"),
        (course_id, "samolot", "airplane",
         "Lecimy samolotem do Hiszpanii na wakacje.",
         "We are flying to Spain by ... for the holidays.",
         "NOWE"),
        (course_id, "biuro", "office",
         "Pracuję w biurze na trzecim piętrze.",
         "I work in an ... on the third floor.",
         "NOWE"),
        (course_id, "zdrowie", "health",
         "Zdrowie jest najważniejsze w życiu.",
         "... is the most important thing in life.",
         "NOWE"),
        (course_id, "internet", "internet",
         "Nie wyobrażam sobie życia bez dostępu do internetu.",
         "I can't imagine life without access to the ....",
         "NOWE"),
        (course_id, "język", "language",
         "Uczę się nowego języka obcego.",
         "I'm learning a new foreign ....",
         "NOWE"),
        (course_id, "sukces", "success",
         "Ciężka praca prowadzi do sukcesu.",
         "Hard work leads to ....",
         "NOWE"),
        (course_id, "wyzwanie", "challenge",
         "Nowa praca to dla mnie duże wyzwanie.",
         "The new job is a big ... for me.",
         "NOWE"),
        (course_id, "doświadczenie", "experience",
         "Mam duże doświadczenie w tej branży.",
         "I have a lot of ... in this industry.",
         "NOWE"),
        (course_id, "projekt", "project",
         "Pracujemy nad ważnym projektem dla klienta.",
         "We are working on an important ... for a client.",
         "NOWE"),
        (course_id, "zespół", "team",
         "Nasz zespół składa się z pięciu osób.",
         "Our ... consists of five people.",
         "NOWE"),
        (course_id, "przyjaźń", "friendship",
         "Nasza przyjaźń trwa już ponad dekadę.",
         "Our ... has lasted over a decade.",
         "NOWE"),
        (course_id, "rodzina", "family",
         "Rodzina jest dla mnie najważniejsza.",
         "... is the most important to me.",
         "NOWE"),
        (course_id, "bezpieczeństwo", "safety",
         "Bezpieczeństwo w pracy jest priorytetem.",
         "... at work is a priority.",
         "NOWE"),
        (course_id, "energia", "energy",
         "Czuję, że mam dzisiaj dużo energii.",
         "I feel like I have a lot of ... today.",
         "NOWE"),
        (course_id, "technologia", "technology",
         "Nowa technologia zmienia nasz sposób życia.",
         "New ... is changing the way we live.",
         "NOWE"),
        (course_id, "edukacja", "education",
         "Edukacja jest kluczem do sukcesu.",
         "... is the key to success.",
         "NOWE"),
        (course_id, "środowisko", "environment",
         "Musimy dbać o nasze środowisko naturalne.",
         "We must take care of our natural ....",
         "NOWE"),
        (course_id, "kultura", "culture",
         "Interesuję się kulturą Japonii.",
         "I'm interested in Japanese ....",
         "NOWE"),
        (course_id, "historia", "history",
         "Historia tego miasta jest bardzo bogata.",
         "The ... of this city is very rich.",
         "NOWE"),
        (course_id, "gospodarka", "economy",
         "Gospodarka kraju rośnie w siłę.",
         "The country's ... is growing stronger.",
         "NOWE"),
        (course_id, "przyroda", "nature",
         "Uwielbiam spędzać czas na łonie przyrody.",
         "I love spending time in ....",
         "NOWE"),
    ]

    # Dodawanie słówek do kursu B1
    course_id = course_ids['B1']
    words_b1 = [
        (course_id, "przedsiębiorstwo", "enterprise",
         "Pracuję w dużym przedsiębiorstwie międzynarodowym.",
         "I work in a large international ....",
         "NOWE"),
        (course_id, "inwestycja", "investment",
         "Ta inwestycja przyniesie duże zyski.",
         "This ... will bring significant profits.",
         "NOWE"),
        (course_id, "negocjacje", "negotiations",
         "Negocjacje z nowym klientem były trudne.",
         "The ... with the new client were tough.",
         "NOWE"),
        (course_id, "innowacja", "innovation",
         "Firma jest znana z wprowadzania innowacji.",
         "The company is known for introducing ....",
         "NOWE"),
        (course_id, "strategia", "strategy",
         "Musimy opracować nową strategię marketingową.",
         "We need to develop a new marketing ....",
         "NOWE"),
        (course_id, "zarządzanie", "management",
         "Zarządzanie czasem to klucz do efektywności.",
         "Time ... is the key to efficiency.",
         "NOWE"),
        (course_id, "społeczeństwo", "society",
         "Żyjemy w społeczeństwie informacyjnym.",
         "We live in an information ....",
         "NOWE"),
        (course_id, "odpowiedzialność", "responsibility",
         "Mam dużą odpowiedzialność w pracy.",
         "I have a lot of ... at work.",
         "NOWE"),
        (course_id, "wniosek", "conclusion",
         "Doszedłem do wniosku, że muszę zmienić pracę.",
         "I came to the ... that I need to change jobs.",
         "NOWE"),
        (course_id, "analiza", "analysis",
         "Przeprowadziliśmy szczegółową analizę danych.",
         "We conducted a detailed data ....",
         "NOWE"),
        (course_id, "konsument", "consumer",
         "Konsument jest najważniejszy dla naszej firmy.",
         "The ... is the most important for our company.",
         "NOWE"),
        (course_id, "rozwiązanie", "solution",
         "Musimy znaleźć rozwiązanie tego problemu.",
         "We need to find a ... to this problem.",
         "NOWE"),
        (course_id, "zjawisko", "phenomenon",
         "To zjawisko jest trudne do wyjaśnienia.",
         "This ... is hard to explain.",
         "NOWE"),
        (course_id, "wymaganie", "requirement",
         "Spełniam wszystkie wymagania na to stanowisko.",
         "I meet all the ... for this position.",
         "NOWE"),
        (course_id, "postęp", "progress",
         "Robimy duży postęp w projekcie.",
         "We are making significant ... in the project.",
         "NOWE"),
        (course_id, "badanie", "research",
         "Prowadzimy badanie rynku od trzech miesięcy.",
         "We have been conducting market ... for three months.",
         "NOWE"),
        (course_id, "dystrybucja", "distribution",
         "Dystrybucja produktów odbywa się co tydzień.",
         "Product ... takes place every week.",
         "NOWE"),
        (course_id, "inspiracja", "inspiration",
         "Szukam inspiracji do nowego projektu.",
         "I'm looking for ... for the new project.",
         "NOWE"),
        (course_id, "współpraca", "collaboration",
         "Współpraca między działami jest kluczowa.",
         "... between departments is crucial.",
         "NOWE"),
        (course_id, "ochrona", "protection",
         "Ochrona danych osobowych jest bardzo ważna.",
         "Data ... is very important.",
         "NOWE"),
        (course_id, "uwarunkowanie", "conditioning",
         "Uwarunkowania społeczne wpływają na nasze decyzje.",
         "Social ... influence our decisions.",
         "NOWE"),
        (course_id, "motywacja", "motivation",
         "Moja motywacja do nauki języków jest wysoka.",
         "My ... to learn languages is high.",
         "NOWE"),
        (course_id, "sukcesja", "succession",
         "Plan sukcesji jest niezbędny w firmie rodzinnej.",
         "A ... plan is essential in a family business.",
         "NOWE"),
        (course_id, "efektywność", "efficiency",
         "Musimy poprawić efektywność naszej pracy.",
         "We need to improve our ....",
         "NOWE"),
        (course_id, "innowacyjność", "innovativeness",
         "Innowacyjność jest kluczem do przewagi konkurencyjnej.",
         "... is the key to competitive advantage.",
         "NOWE"),
        (course_id, "zrównoważony", "sustainable",
         "Rozwój zrównoważony jest ważny dla środowiska.",
         "A ... development is important for the environment.",
         "NOWE"),
        (course_id, "przedsiębiorczość", "entrepreneurship",
         "Przedsiębiorczość jest promowana w naszej szkole.",
         "... is promoted in our school.",
         "NOWE"),
        (course_id, "dostępność", "availability",
         "Sprawdzamy dostępność produktów w magazynie.",
         "We are checking the ... of products in the warehouse.",
         "NOWE"),
        (course_id, "rentowność", "profitability",
         "Rentowność projektu jest pod znakiem zapytania.",
         "The ... of the project is questionable.",
         "NOWE"),
        (course_id, "różnorodność", "diversity",
         "Różnorodność kulturowa wzbogaca społeczeństwo.",
         "Cultural ... enriches society.",
         "NOWE"),
    ]

    # Dodawanie słówek do kursu B2
    course_id = course_ids['B2']
    words_b2 = [
        (course_id, "paradygmat", "paradigm",
         "Zmiana paradygmatu w nauce jest rzadkim zjawiskiem.",
         "A shift in ... in science is a rare phenomenon.",
         "NOWE"),
        (course_id, "interdyscyplinarny", "interdisciplinary",
         "Projekt ma charakter interdyscyplinarny.",
         "The project has an ... character.",
         "NOWE"),
        (course_id, "implementacja", "implementation",
         "Implementacja nowego systemu zajmie kilka miesięcy.",
         "The ... of the new system will take several months.",
         "NOWE"),
        (course_id, "konsekwencja", "consequence",
         "Musisz być świadomy konsekwencji swoich decyzji.",
         "You need to be aware of the ... of your decisions.",
         "NOWE"),
        (course_id, "dychotomia", "dichotomy",
         "Istnieje dychotomia między teorią a praktyką.",
         "There is a ... between theory and practice.",
         "NOWE"),
        (course_id, "egzemplifikacja", "exemplification",
         "Egzemplifikacja tej teorii jest widoczna w badaniach.",
         "The ... of this theory is evident in the research.",
         "NOWE"),
        (course_id, "nomenklatura", "nomenclature",
         "Nomenklatura w tej dziedzinie jest skomplikowana.",
         "The ... in this field is complicated.",
         "NOWE"),
        (course_id, "antagonizm", "antagonism",
         "Antagonizm między grupami jest coraz silniejszy.",
         "The ... between the groups is growing stronger.",
         "NOWE"),
        (course_id, "kognitywny", "cognitive",
         "Procesy kognitywne są badane przez psychologów.",
         "... processes are studied by psychologists.",
         "NOWE"),
        (course_id, "dyskurs", "discourse",
         "Dyskurs publiczny na ten temat jest bardzo emocjonalny.",
         "The public ... on this topic is very emotional.",
         "NOWE"),
        (course_id, "paradoks", "paradox",
         "To jest paradoks, który trudno wyjaśnić.",
         "This is a ... that is hard to explain.",
         "NOWE"),
        (course_id, "pragmatyczny", "pragmatic",
         "Potrzebujemy pragmatycznego podejścia do problemu.",
         "We need a ... approach to the problem.",
         "NOWE"),
        (course_id, "spekulacja", "speculation",
         "Spekulacje na temat przyszłości firmy są nieuniknione.",
         "... about the company's future is inevitable.",
         "NOWE"),
        (course_id, "konflikt", "conflict",
         "Konflikt interesów może być problematyczny.",
         "A ... of interest can be problematic.",
         "NOWE"),
        (course_id, "kontyngencja", "contingency",
         "Musimy przygotować plan na wypadek kontyngencji.",
         "We need to prepare a plan in case of ....",
         "NOWE"),
        (course_id, "hipoteza", "hypothesis",
         "Hipoteza została potwierdzona eksperymentem.",
         "The ... was confirmed by the experiment.",
         "NOWE"),
        (course_id, "aksjomat", "axiom",
         "Aksjomaty są podstawą matematyki.",
         "... are the foundation of mathematics.",
         "NOWE"),
        (course_id, "aplikacja", "application",
         "Ta teoria ma praktyczne aplikacje.",
         "This theory has practical ....",
         "NOWE"),
        (course_id, "weryfikacja", "verification",
         "Weryfikacja danych jest konieczna.",
         "... of the data is necessary.",
         "NOWE"),
        (course_id, "metodologia", "methodology",
         "Musimy zmienić naszą metodologię badawczą.",
         "We need to change our research ....",
         "NOWE"),
        (course_id, "kompatybilność", "compatibility",
         "Kompatybilność systemów jest kluczowa.",
         "... of systems is crucial.",
         "NOWE"),
        (course_id, "redukcja", "reduction",
         "Redukcja kosztów jest niezbędna.",
         "... of costs is essential.",
         "NOWE"),
        (course_id, "syntetyczny", "synthetic",
         "Syntetyczne materiały są używane w produkcji.",
         "... materials are used in production.",
         "NOWE"),
        (course_id, "egzemplarz", "specimen",
         "To jest unikalny egzemplarz tej książki.",
         "This is a unique ... of this book.",
         "NOWE"),
        (course_id, "transcendentalny", "transcendental",
         "Filozofia transcendentalna jest trudna do zrozumienia.",
         "The ... philosophy is hard to understand.",
         "NOWE"),
        (course_id, "interferencja", "interference",
         "Interferencja sygnałów powoduje zakłócenia.",
         "... of signals causes disruptions.",
         "NOWE"),
        (course_id, "kwantyfikacja", "quantification",
         "Kwantyfikacja ryzyka jest skomplikowana.",
         "... of risk is complicated.",
         "NOWE"),
        (course_id, "konwergencja", "convergence",
         "Konwergencja technologii wpływa na rynek.",
         "... of technologies affects the market.",
         "NOWE"),
        (course_id, "dysjunkcja", "disjunction",
         "W logice dysjunkcja jest operatorem 'lub'.",
         "In logic, ... is the 'or' operator.",
         "NOWE"),
        (course_id, "ewaluacja", "evaluation",
         "Ewaluacja wyników nastąpi w przyszłym tygodniu.",
         "... of the results will take place next week.",
         "NOWE"),
        (course_id, "abstrakcja", "abstraction",
         "Abstrakcja jest kluczowa w sztuce nowoczesnej.",
         "... is key in modern art.",
         "NOWE"),
    ]

    # Łączymy wszystkie słówka
    all_words = words_a1 + words_a2 + words_b1 + words_b2

    # Dodawanie wszystkich słówek do bazy danych
    cursor.executemany('''
        INSERT INTO words (course_id, word_pl, word_en, example_pl, example_en, category)
        VALUES (?, ?, ?, ?, ?, ?)
    ''', all_words)

    connection.commit()
    connection.close()
    print("Baza danych została zainicjalizowana i słówka zostały dodane.")

if __name__ == "__main__":
    initialize_database()
